version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: ai_doctor_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ai_doctor_network

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres123@postgres:5432/ai_doctor_db
      - SECRET_KEY=your-super-secret-key-change-in-production
      - OPENAI_API_KEY=your-openai-api-key
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
      - uploaded_files:/app/uploaded_files
    networks:
      - ai_doctor_network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - ai_doctor_network

volumes:
  postgres_data:
  uploaded_files:

networks:
  ai_doctor_network:
    driver: bridge